### PR TITLE
Added french localization for Commits

### PR DESCRIPTION
**Pull request by qmathe**
Switched to Base localization with English as development language

Fixed language directory lookup to be compatible with Base localization and preferred localizations

### CODE REVIEW

**Comment by ericwa** [comment]
Hmm.. this test is failing for some reason?
```
- (void) testSelectiveRedoCommitDescriptor
{
	UKNotNil([COCommitDescriptor registeredDescriptorForIdentifier: @"org.etoile.CoreObject.selective-redo"]);
}
```

**Comment by ericwa** [comment]
I think I fixed it

**Comment by qmathe** [comment]
I committed the correct fix for the failing test in the master. 

I also added a little explanation that makes it clearer why the preferred localizations have to be requested to the main bundle.

Ideally we should have some tests to cover this, but this would require some refactoring to support a method like +reloadCommitDescriptorsForPreferredLocalizations:.

**Comment by qmathe** [comment]
Thanks for the review btw :)

**Pull request merged**
