### PR TITLE
COObject+Accessors rewrite

### PR DESCRIPTION
**Pull request by ericwa**
See commit comments

### CODE REVIEW

**Comment by qmathe** [comment]
The code looks good, feel free to merge it. Thanks a lot for working on that :)

**Comment by ericwa** [comment]
thanks, I think I fixed all of the style problems.

**Comment by qmathe** [comment]
I just took a look at the performance improvements.

At launch time, the time spent in +resolveInstanceMethod: went down from 200/300 ms to 1ms! 

The performance improvement is also visible elsewhere sometimes. For example, when navigating accross a big history, this change can cut 50ms too.

Beside PropertyToSetter(), the two following lines were also important bottlenecks:

NSString *attributes = [NSString stringWithUTF8String: property_getAttributes(property)];
BOOL isDynamic = ([attributes rangeOfString: @"D"].location != NSNotFound);

**Comment by ericwa** [comment]
Nice. The `+resolveInstanceMethod:` changes should only affect startup time (or the first time classes are used).

The change in `genericSetter` will make setters faster since there's no longer any NSString manipulation, and no use of format strings, just creating an NSString from a C string.

**Pull request merged**
